using AdventureCreator.Core.Model;

namespace AdventureCreator.Core.Engine;

/// <summary>
/// Ids and default texts of the engine's built-in messages. Authors (and importers, for system messages)
/// override them through <see cref="Adventure.Messages"/>.
/// Placeholders: {noun1} {noun2} {The noun1} {verb} {adverb} {direction} {score} {max} {turns} {word} {count}.
/// </summary>
public static class Msg
{
    public const string Dark = "Dark";
    public const string YouCanSee = "YouCanSee";
    public const string Exits = "Exits";
    public const string NoExits = "NoExits";
    public const string CantGo = "CantGo";
    public const string DontUnderstand = "DontUnderstand";
    public const string UnknownWord = "UnknownWord";
    public const string CantDoThat = "CantDoThat";
    public const string NotHere = "NotHere";
    public const string Ok = "Ok";
    public const string Taken = "Taken";
    public const string Dropped = "Dropped";
    public const string AlreadyCarrying = "AlreadyCarrying";
    public const string NotCarrying = "NotCarrying";
    public const string CantTake = "CantTake";
    public const string TooMany = "TooMany";
    public const string TooHeavy = "TooHeavy";
    public const string Carrying = "Carrying";
    public const string CarryingNothing = "CarryingNothing";
    public const string Wearing = "Wearing";
    public const string Worn = "Worn";
    public const string NotWearable = "NotWearable";
    public const string Removed = "Removed";
    public const string NotWorn = "NotWorn";
    public const string Score = "Score";
    public const string Turns = "Turns";
    public const string NothingSpecial = "NothingSpecial";
    public const string Opened = "Opened";
    public const string Closed = "Closed";
    public const string AlreadyOpen = "AlreadyOpen";
    public const string AlreadyClosed = "AlreadyClosed";
    public const string NotOpenable = "NotOpenable";
    public const string Locked = "Locked";
    public const string Unlocked = "Unlocked";
    public const string IsLocked = "IsLocked";
    public const string NoKey = "NoKey";
    public const string WrongKey = "WrongKey";
    public const string ContainerClosed = "ContainerClosed";
    public const string PutIn = "PutIn";
    public const string PutOn = "PutOn";
    public const string NotContainer = "NotContainer";
    public const string ContainerFull = "ContainerFull";
    public const string Eaten = "Eaten";
    public const string NotEdible = "NotEdible";
    public const string Drunk = "Drunk";
    public const string NothingToRead = "NothingToRead";
    public const string NoReply = "NoReply";
    public const string Waited = "Waited";
    public const string Which = "Which";
    public const string NothingToUndo = "NothingToUndo";
    public const string Undone = "Undone";
    public const string NoHints = "NoHints";
    public const string Saved = "Saved";
    public const string Restored = "Restored";
    public const string GameOverWin = "GameOverWin";
    public const string GameOverLose = "GameOverLose";
    public const string NothingToTake = "NothingToTake";
    public const string NothingToDrop = "NothingToDrop";
    public const string DoorClosed = "DoorClosed";
    public const string SwitchedOn = "SwitchedOn";
    public const string SwitchedOff = "SwitchedOff";
    public const string NotSwitchable = "NotSwitchable";
    public const string Pronoun = "Pronoun";
    public const string CorrectedSpelling = "CorrectedSpelling";
    public const string AdverbNoEffect = "AdverbNoEffect";
    public const string Violence = "Violence";
    public const string Nothing = "Nothing";
    public const string CantSeeInDark = "CantSeeInDark";
    public const string Inside = "Inside";
    public const string On = "On";
    public const string Empty = "Empty";
    public const string BadlyHurt = "BadlyHurt";
    public const string Health = "Health";
    public const string Flooded = "Flooded";
    public const string FloodedHere = "FloodedHere";
    public const string FloodRises = "FloodRises";
    public const string Drained = "Drained";
    public const string Drowned = "Drowned";
    public const string SweptOut = "SweptOut";
    public const string TrapSense = "TrapSense";
    public const string TrapFound = "TrapFound";
    public const string TrapAlreadyFound = "TrapAlreadyFound";
    public const string TrapSprung = "TrapSprung";
    public const string TrapAvoided = "TrapAvoided";
    public const string NothingFound = "NothingFound";

    public static readonly IReadOnlyDictionary<string, string> Defaults = new Dictionary<string, string>
    {
        [Dark] = "It is pitch dark. You can't see a thing.",
        [YouCanSee] = "You can see {list} here.",
        [Exits] = "Exits: {list}.",
        [NoExits] = "There are no obvious exits.",
        [CantGo] = "You can't go that way.",
        [DontUnderstand] = "I don't understand that.",
        [UnknownWord] = "I don't know the word \"{word}\".",
        [CantDoThat] = "You can't do that.",
        [NotHere] = "You can't see any such thing.",
        [Ok] = "OK.",
        [Taken] = "Taken.",
        [Dropped] = "Dropped.",
        [AlreadyCarrying] = "You already have {the noun1}.",
        [NotCarrying] = "You're not carrying {the noun1}.",
        [CantTake] = "You can't take {the noun1}.",
        [TooMany] = "You're carrying too many things already.",
        [TooHeavy] = "{The noun1} is too heavy for you to carry as well.",
        [Carrying] = "You are carrying {list}.",
        [CarryingNothing] = "You are empty-handed.",
        [Wearing] = "You are wearing {list}.",
        [Worn] = "You put on {the noun1}.",
        [NotWearable] = "You can't wear {the noun1}.",
        [Removed] = "You take off {the noun1}.",
        [NotWorn] = "You're not wearing {the noun1}.",
        [Score] = "You have scored {score} out of a possible {max}, in {turns} turns.",
        [Turns] = "You have taken {turns} turns.",
        [NothingSpecial] = "You see nothing special about {the noun1}.",
        [Opened] = "You open {the noun1}.",
        [Closed] = "You close {the noun1}.",
        [AlreadyOpen] = "{The noun1} is already open.",
        [AlreadyClosed] = "{The noun1} is already closed.",
        [NotOpenable] = "{The noun1} can't be opened.",
        [Locked] = "You lock {the noun1}.",
        [Unlocked] = "You unlock {the noun1}.",
        [IsLocked] = "{The noun1} is locked.",
        [NoKey] = "You have nothing to unlock {the noun1} with.",
        [WrongKey] = "{The noun2} doesn't fit.",
        [ContainerClosed] = "{The noun2} is closed.",
        [PutIn] = "You put {the noun1} in {the noun2}.",
        [PutOn] = "You put {the noun1} on {the noun2}.",
        [NotContainer] = "You can't put things in {the noun2}.",
        [ContainerFull] = "There's no room in {the noun2}.",
        [Eaten] = "You eat {the noun1}. Delicious.",
        [NotEdible] = "That's plainly inedible.",
        [Drunk] = "You drink {the noun1}.",
        [NothingToRead] = "There's nothing written on {the noun1}.",
        [NoReply] = "There is no reply.",
        [Waited] = "Time passes.",
        [Which] = "Which do you mean, {list}?",
        [NothingToUndo] = "There is nothing to undo.",
        [Undone] = "[Previous turn undone.]",
        [NoHints] = "There are no hints available right now.",
        [Saved] = "Game saved.",
        [Restored] = "Game restored.",
        [GameOverWin] = "*** You have won ***",
        [GameOverLose] = "*** You have died ***",
        [NothingToTake] = "There is nothing here to take.",
        [NothingToDrop] = "You have nothing to drop.",
        [DoorClosed] = "{The door} is closed.",
        [SwitchedOn] = "You switch on {the noun1}.",
        [SwitchedOff] = "You switch off {the noun1}.",
        [NotSwitchable] = "That's not something you can switch.",
        [Pronoun] = "(assuming {the noun1})",
        [CorrectedSpelling] = "(taking \"{word}\" to mean \"{corrected}\")",
        [AdverbNoEffect] = "Doing it {adverb} makes no difference.",
        [Violence] = "Violence isn't the answer to this one.",
        [Nothing] = "nothing",
        [CantSeeInDark] = "It's too dark to see.",
        [Inside] = "In {the noun1} you can see {list}.",
        [On] = "On {the noun1} you can see {list}.",
        [Empty] = "{The noun1} is empty.",
        [BadlyHurt] = "You are badly hurt.",
        [Health] = "Your health is {health} out of {maxhealth}.",
        [Flooded] = "{room} is flooded. You can't go there without a boat or diving gear.",
        [FloodedHere] = "Water fills this place, cold and deep.",
        [FloodRises] = "Water comes surging in!",
        [Drained] = "The water drains away.",
        [Drowned] = "The water closes over your head. You have drowned.",
        [SweptOut] = "The rising water sweeps you away to {room}!",
        [TrapSense] = "You have an uneasy feeling about this place.",
        [TrapFound] = "Searching carefully, you discover a trap – and step well clear of it.",
        [TrapAlreadyFound] = "You've already found the trap here.",
        [TrapSprung] = "Click. Too late, you realise you've sprung a trap!",
        [TrapAvoided] = "You step carefully around the trap.",
        [NothingFound] = "You find nothing of interest.",
    };
}
